apiVersion: v1
kind: Pod
metadata:
 name: "maciej-devel"
spec:
  restartPolicy: Never
  containers:
    - name: gpu-container
      image: "eu.gcr.io/gpu-kubernetes-nomagic-io/pytorch:maciej-9"
      imagePullPolicy: Always
      resources:
        requests:
            cpu: "1000m"
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia
          name: lib
        - mountPath: /mnt
          name: mnt
      command: [ "/bin/bash", "-c", "--", "systemctl start ssh; jupyter notebook --notebook-dir=/ --ip='0.0.0.0' --allow-root --port=8888 --no-browser --NotebookApp.token='MaciejMaciej'"]


  volumes:
    - hostPath:
        path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90/bin/
      name: bin
    - hostPath:
        path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90/
      name: lib
    - hostPath:
        path: /home/jaskowski/projects/atari-objects
      name: mnt

